### ISSUE TITLE
Push updated release

### ISSUE THREAD

**Issue by bilderbuchi** [modelica-tools/atom-language-modelica#1]
Hi @raphaelchenouard 
I just discovered your modelica package for Atom, very nice/practical!
Would you mind publishing another release so that the contents of the last commit (10ad7d9e4ff9ca8c01ac3c18e623a6e97e717233) become visible to the Atom package manager? Also, did you make any further improvements you could share?

**Comment by thorade** [comment]
A new release has been pushed:
https://atom.io/packages/language-modelica
Closing this issue.

**Notes:**
`apm publish major/minor/patch` will change the version in the package.json file, create a commit, create a tag and push it. In order to be able to do this, `apm publish` has to be run from a git enabled command prompt.

Some of these steps can alternatively be done manually, then use something like `apm publish 0.2.0`.

**Comment by bilderbuchi** [comment]
nice, thanks!
