### ISSUE TITLE
doc view for package

### ISSUE THREAD

**Issue by thorade** [modelica-tools/atom-language-modelica#25]
Here is a package with many functions, and some have a documentation:
https://github.com/iea-annex60/modelica-annex60/blob/master/Annex60/Media/Air.mo
When opening that in the docview, all documentation is written in one big block.
Would it be possible to have e.g. a hrule as separator between the doc for different functions/models? And the function name, but only if the documentation is not empty?

**Comment by tshort** [comment]
<img width="354" alt="docview" src="https://cloud.githubusercontent.com/assets/636420/10775726/41aaf222-7ce1-11e5-830f-1244d8365c0f.png">

I did not try to strike the function name if it did not have documentation. I'd like to leave it the way it is because I like to see that the function/model is there even if it's not documented.

**Comment by thorade** [comment]
I am fine with having all function names.
Currently, there seems to be an issue, because some function names do not show up. Maybe related to redeclare?
In the below screenshot the functions `density` and `dynamicViscosity` do not have any header.

![atom_docview](https://cloud.githubusercontent.com/assets/314571/10784216/1cb398bc-7d5d-11e5-8a21-315e6f3b1a1a.png)

**Comment by tshort** [comment]
How about a new issue for that one, @thorade.

**Comment by thorade** [comment]
closed by #26
